tox: explicitly test with Python 3.2 and 3.3
We've had a number of issues with subtle differences between Python
version 3.2 and 3.3. Python 3.2 is what Jenkins had installed (it's
part of Ubuntu 12.04 LTS) and Python 3.3 is what Lars and I had
installed locally.

We've now installed Python 3.3 on Jenkins as well and can thus
explicitly add test coverage to that version. Older and newer versions
of Python for Ubuntu can be found here:

  https://launchpad.net/~fkrull/+archive/deadsnakes

For Debian, you can enable more than one distribution at the same
time, e.g., enabling wheezy and jessie (testing) at the same time.

If you don't have all the Python versions installed, tox will report
this in the summary:

  $ tox
  # ...
    py27: commands succeeded
  ERROR:   py32: InterpreterNotFound: python3.2
    py33: commands succeeded
    pep8: commands succeeded
    pyflakes: commands succeeded
    full: commands succeeded
    doc: commands succeeded

This should make it clear for contributors exactly which Python
versions we support.